/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        /*
        //to test binary search function
        int [] testArr = {4, 8, 15, 16, 23, 42} ;
        System.out.println(binarySearch(testArr , 15));

         */
    }

    public static int binarySearch(int [] arr , int value ){

        int low = 0 ;
        int high = arr.length-1 ;
        while (low <= high) {

            int mid = low + (high - low) / 2;

            if (arr[mid] == value)
                return mid;

            if (arr[mid] < value)
                low = mid + 1;


            else
                high = mid - 1;
        }

        return -1;
    }

}
