/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LinkedList;

import org.junit.jupiter.api.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testInstantiateEmptyLinkedList(){
        LinkedList testList = new LinkedList();
        assertEquals("empty" , testList.toString());
    }
    @Test
    public void testInsert(){
        LinkedList testList = new LinkedList();
        testList.insert(1);
        testList.insert(2);
        testList.insert(3);
        assertEquals("{ 3 } -> { 2 } -> { 1 } -> NULL" , testList.toString());
    }
    @Test
    public void testHead(){
        LinkedList testList = new LinkedList();
        testList.insert(1);
        testList.insert(2);
        testList.insert(3);
        assertEquals(3 , testList.getHead());
    }

    @Test
    public void testIncludes(){
        LinkedList testList = new LinkedList();
        testList.insert(1);
        testList.insert(2);
        testList.insert(3);
        assertEquals(true , testList.includes(2));
        assertEquals(false , testList.includes(10));
    }
    @Test
    public void testToString(){
        LinkedList testList = new LinkedList();
        testList.insert(-7);
        testList.insert(2);
        testList.insert(5);
        testList.insert(1);
        testList.insert(2);
        testList.insert(3);
        assertEquals("{ 3 } -> { 2 } -> { 1 } -> { 5 } -> { 2 } -> { -7 } -> NULL" , testList.toString());
    }


}
