package LinkedList;/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {


    }

    public  static LinkedList zipLists(LinkedList list1 , LinkedList list2){
        LinkedList zipLinkedList = new LinkedList() ;
        int biggerLength = list1.getLength() >= list2.getLength() ? list1.getLength() : list2.getLength() ;
        for(int i = 1 ; i<=biggerLength ; i++){
            if(list1.getLength()-i >= 0)
                zipLinkedList.append(list1.kthFromEnd(list1.getLength()-i));
            if(list2.getLength()-i >= 0)
                zipLinkedList.append(list2.kthFromEnd(list2.getLength()-i));
        }
        return zipLinkedList ;
    }
}
