/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Graph.Challenge;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Graph graph = new Graph();
        graph.addVertex("Qusay");
        graph.addVertex("Ali");
        graph.addVertex("Hadi");
        graph.addVertex("Jafar");

        graph.addEdge("Qusay" , "Ali");
        graph.addEdge("Qusay" , "Hadi");
        graph.addEdge("Qusay" , "Jafar");

//        System.out.println(graph.toString());

//        System.out.println(graph.bft("Qusay").toString());
//        System.out.println(graph.dft("Qusay").toString());

        System.out.println(graph.getNeighbors("Qusay"));

    }
}
