/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import LinkedList.LinkedList ;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {


    }
}
