/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Insertion.Sort.Challenge;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @DisplayName("Test Insertion Sort")
    @Test
    public void testInsertionSort(){
        Sort testSort = new Sort();
        List<Integer> arr = new ArrayList<>();
        arr.add(5);
        arr.add(3);
        arr.add(2);
        assertEquals("[2, 3, 5]" , testSort.insertionSort(arr).toString());
    }

}
