/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TreeDataStructure;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        BinarySearchTree binarySearchTree = new BinarySearchTree();
        binarySearchTree.setRoot(new Node(1));
        binarySearchTree.add(8);
        binarySearchTree.add(5);
        binarySearchTree.add(2);
        binarySearchTree.add(5);
        binarySearchTree.add(5);
        System.out.println(binarySearchTree.getSumOddNums());
    }
}
