/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TreeDataStructure;

import java.sql.Time;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {


    }
}
