/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StackQueue;

import org.checkerframework.checker.units.qual.A;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {



    }
}
