/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StackQueue;

import org.checkerframework.checker.units.qual.A;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

//        Animal cat = new Animal("Cat");
//        Animal dog = new Animal("Dog");
        AnimalShelter animalShelter = new AnimalShelter() ;
        animalShelter.enqueue("cat");
        animalShelter.enqueue("dog");
        animalShelter.enqueue("dog");
        animalShelter.dequeue("dog");
        animalShelter.dequeue("dog");
        System.out.println(animalShelter.toString());
//        System.out.println(newAnimal.getType());
    }
}
