/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LinkedList;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testKbiggerThanLength(){
        LinkedList testList = new LinkedList() ;
        testList.append(1);
        testList.append(2);
        testList.append(3);
        testList.append(4);
        assertEquals("Exception" , testList.kthFromEnd(6));
    }
    @Test
    public void testKequalLength(){
        LinkedList testList = new LinkedList() ;
        testList.append(1);
        testList.append(2);
        testList.append(3);
        testList.append(4);
        assertEquals("Exception" , testList.kthFromEnd(4));
    }
    @Test
    public void testKnegative(){
        LinkedList testList = new LinkedList() ;
        testList.append(1);
        testList.append(2);
        testList.append(3);
        testList.append(4);
        assertEquals("Exception" , testList.kthFromEnd(-7));
    }
    @Test
    public void testLengthEq1(){
        LinkedList testList = new LinkedList() ;
        testList.append(1);
        assertEquals(1 , testList.kthFromEnd(0));
    }
    @Test
    public void testKinMiddle(){
        LinkedList testList = new LinkedList() ;
        testList.append(1);
        testList.append(2);
        testList.append(3);
        testList.append(4);
        testList.append(5);
        assertEquals(3 , testList.kthFromEnd(2));
    }

}
